### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by michaelmior**
This removes the Travis CI configuration and runs tests on GitHub Actions instead. For now I've just removed Codecov, but this at least gets the tests running again. Also supercedes #18.

### CODE REVIEW

**Comment by michaelmior** [comment]
Strange. Tests on Python 3.7 [passed on my own fork](https://github.com/michaelmior/jsonsubschema/actions/runs/9132258342).

**Comment by shinnar** [comment]
Thanks so much for this!

Two comments:
- I would suggest just removing python 3.7 support (so removing it from the matrix), as Python 3.7 was EOL in 2023.
- The package currently specifies its dependencies in setup.py.  Why does this PR introduce a requirements.txt file as well?  If the requirements.txt file is desirable for a particular use case, then it should be read and used in setup.py as well. I am not against having it, I would just prefer to reduce redundant dependency specifications that can easily get out of date.

**Comment by michaelmior** [comment]
Agreed that Python 3.7 should just be removed. I would also suggest adding 3.11 and maybe 3.12. requirements.txt was added because it's necessary for caching support in GitHub Actions. Agreed that the duplication is bad and reading that in setup.py seems like a good solution.

**Comment by michaelmior** [comment]
I will say however that the two are intended for different purposes and [arguably should be kept separate](https://stackoverflow.com/a/33685899/123695).

**Comment by michaelmior** [comment]
Also, apparently specifying a single `.` in the requirements.txt will cause it to read from setup.py, which I think would be a better alternative.

**Comment by michaelmior** [comment]
Okay, I've updated the PR to test against Python 3.8-3.12 and removed the duplication in `requirements.txt`.

**Comment by shinnar** [comment]
Merged!
Thanks!

**Pull request merged**
